In [15]:
from sys import path
path.append(r"D:\\SmartCloudFuture")

from SCTK import scada

In [17]:
scada.algo_module

AttributeError: module 'SCTK.scada' has no attribute 'algo_module'

In [5]:
get_pe_ttm('600570', '20170606')

In [37]:
from pymongo import MongoClient

conn = MongoClient('127.0.0.1', 27017)
db = conn.stockdata
incomedb = db['income']

In [38]:
result = incomedb.find({"code":"600570.XSHG"})

In [39]:
import pandas as pd

df = pd.DataFrame(list(result))

In [40]:
df

,_id,administration_expense,asset_impairment_loss,basic_eps,ci_minority_owners,ci_parent_company_owners,code,commission_expense,commission_income,diluted_eps,...,refunded_premiums,reinsurance_cost,sale_expense,statDate,statDate_1,total_composite_income,total_operating_cost,total_operating_revenue,total_profit,withdraw_insurance_contract_reserve
0,5ac57fb02e565406381d089f,1.650519e+07,NaN,NaN,NaN,NaN,600570.XSHG,NaN,NaN,NaN,...,NaN,NaN,5.326427e+06,2005-03-31,2005-03-31,NaN,4.169257e+07,3.861545e+07,2.471650e+05,NaN
1,5ac57fb02e565406381d08a0,1.350073e+07,0.000000e+00,NaN,0.000000e+00,0.000000e+00,600570.XSHG,0.0,0.0,NaN,...,0.0,0.0,9.026373e+06,2005-06-30,2005-06-30,0.000000e+00,4.834777e+07,4.962814e+07,2.502735e+06,0.0
2,5ac57fb02e565406381d08a1,1.633236e+07,0.000000e+00,NaN,0.000000e+00,0.000000e+00,600570.XSHG,0.0,0.0,NaN,...,0.0,0.0,1.478560e+07,2005-09-30,2005-09-30,0.000000e+00,5.395177e+07,4.878073e+07,-1.067038e+06,0.0
3,5ac57fb02e565406381d08a2,3.588122e+07,0.000000e+00,NaN,0.000000e+00,0.000000e+00,600570.XSHG,0.0,0.0,NaN,...,0.0,0.0,1.260748e+07,2005-12-31,2005-12-31,0.000000e+00,9.805474e+07,9.971500e+07,6.309092e+06,0.0
4,5ac57fb02e565406381d08a3,1.118624e+07,NaN,0.0191,NaN,NaN,600570.XSHG,NaN,NaN,0.0137,...,NaN,NaN,1.395958e+07,2006-03-31,2006-03-31,NaN,5.949652e+07,5.551059e+07,1.853099e+06,NaN
5,5ac57fb02e565406381d08a4,2.365025e+07,2.546915e+06,0.0209,0.000000e+00,0.000000e+00,600570.XSHG,NaN,NaN,0.0163,...,NaN,NaN,1.147031e+07,2006-06-30,2006-06-30,0.000000e+00,8.285141e+07,8.146291e+07,4.676409e+06,NaN
6,5ac57fb02e565406381d08a5,1.898346e+07,0.000000e+00,0.0900,0.000000e+00,0.000000e+00,600570.XSHG,NaN,NaN,0.0700,...,NaN,NaN,1.548291e+07,2006-09-30,2006-09-30,0.000000e+00,6.755671e+07,7.771690e+07,1.415241e+07,NaN
7,5ac57fb02e565406381d08a6,3.815899e+07,6.656682e+06,0.1600,0.000000e+00,0.000000e+00,600570.XSHG,NaN,NaN,0.1900,...,NaN,NaN,1.319190e+07,2006-12-31,2006-12-31,0.000000e+00,1.306259e+08,1.311665e+08,4.150465e+07,NaN
8,5ac57fb02e565406381d08a7,1.675826e+07,NaN,0.0922,NaN,NaN,600570.XSHG,NaN,NaN,0.0922,...,NaN,NaN,1.401888e+07,2007-03-31,2007-03-31,NaN,5.596684e+07,5.925009e+07,1.602855e+07,NaN
9,5ac57fb02e565406381d08a8,2.306086e+07,2.645505e+06,0.1078,0.000000e+00,0.000000e+00,600570.XSHG,NaN,NaN,0.1078,...,NaN,NaN,2.458784e+07,2007-06-30,2007-06-30,0.000000e+00,1.200182e+08,1.255172e+08,2.988806e+07,NaN
10,5ac57fb02e565406381d08a9,2.969795e+07,3.810000e+04,0.2200,0.000000e+00,0.000000e+00,600570.XSHG,NaN,NaN,0.2200,...,NaN,NaN,3.070183e+07,2007-09-30,2007-09-30,0.000000e+00,1.322278e+08,1.561338e+08,4.894864e+07,NaN
11,5ac57fb02e565406381d08aa,7.705690e+07,2.057964e+06,0.2600,0.000000e+00,0.000000e+00,600570.XSHG,NaN,NaN,0.2600,...,NaN,NaN,2.246804e+07,2007-12-31,2007-12-31,0.000000e+00,2.067672e+08,2.315271e+08,4.705567e+07,NaN
12,5ac57fb02e565406381d08ab,3.024180e+07,3.510349e+05,0.1300,NaN,NaN,600570.XSHG,NaN,NaN,0.1300,...,NaN,NaN,2.163227e+07,2008-03-31,2008-03-31,NaN,1.245168e+08,1.495216e+08,2.801362e+07,NaN
13,5ac57fb02e565406381d08ac,3.006031e+07,1.403876e+06,0.0300,0.000000e+00,0.000000e+00,600570.XSHG,NaN,NaN,0.0300,...,NaN,NaN,2.227069e+07,2008-06-30,2008-06-30,0.000000e+00,9.731574e+07,1.115232e+08,7.551398e+06,NaN
14,5ac57fb02e565406381d08ad,3.841346e+07,1.764896e+05,0.1100,0.000000e+00,0.000000e+00,600570.XSHG,NaN,NaN,0.1100,...,NaN,NaN,3.389238e+07,2008-09-30,2008-09-30,0.000000e+00,1.168202e+08,1.430293e+08,3.502918e+07,NaN
15,5ac57fb02e565406381d08ae,1.015926e+08,-1.732956e+06,0.1800,0.000000e+00,0.000000e+00,600570.XSHG,NaN,NaN,0.1800,...,NaN,NaN,2.590820e+07,2008-12-31,2008-12-31,0.000000e+00,2.188555e+08,2.646075e+08,6.589000e+07,NaN
16,5ac57fb02e565406381d08af,2.597913e+07,1.073165e+06,0.1100,NaN,NaN,600570.XSHG,NaN,NaN,0.1100,...,NaN,NaN,2.219355e+07,2009-03-31,2009-03-31,NaN,1.012803e+08,1.195908e+08,3.628342e+07,NaN
17,5ac57fb02e565406381d08b0,3.680308e+07,1.913249e+06,0.0500,0.000000e+00,0.000000e+00,600570.XSHG,NaN,NaN,0.0500,...,NaN,NaN,3.033340e+07,2009-06-30,2009-06-30,0.000000e+00,9.680222e+07,1.298877e+08,4.342704e+07,NaN
18,5ac57fb02e565406381d08b1,4.002534e+07,-3.398468e+05,0.1200,0.000000e+00,0.000000e+00,600570.XSHG,NaN,NaN,0.1200,...,NaN,NaN,2.711301e+07,2009-09-30,2009-09-30,0.000000e+00,1.142544e+08,1.570479e+08,5.920321e+07,NaN
19,5ac57fb02e565406381d08b2,1.121848e+08,5.899604e+04,0.1800,4.360651e+06,2.066964e+08,600570.XSHG,NaN,NaN,0.1800,...,NaN,NaN,5.158045e+07,2009-12-31,2009-12-31,2.110571e+08,2.692821e+08,3.231854e+08,9.376719e+07,NaN
20,5ac57fb02e565406381d08b3,4.459986e+07,3.102105e+04,0.0800,-1.496884e+06,3.479874e+07,600570.XSHG,NaN,NaN,0.0800,...,NaN,NaN,2.535861e+07,2010-03-31,2010-03-31,3.330186e+07,8.620820e+07,1.079588e+08,3.632138e+07,NaN
21,5ac57fb02e565406381d08b4,5.693299e+07,3.165044e+06,0.0063,1.576848e+06,4.151714e+06,600570.XSHG,NaN,NaN,0.0063,...,NaN,NaN,3.531866e+07,2010-06-30,2010-06-30,5.728562e+06,1.663644e+08,1.868096e+08,2.387972e+07,NaN
22,5ac57fb02e565406381d08b5,6.523471e+07,-6.996882e+04,0.1072,2.383394e+06,7.635227e+07,600570.XSHG,NaN,NaN,0.1072,...,NaN,NaN,3.192449e+07,2010-09-30,2010-09-30,7.873566e+07,1.568459e+08,2.151671e+08,7.504538e+07,NaN
23,5ac57fb02e565406381d08b6,1.592635e+08,9.688032e+05,0.1565,5.484606e+05,1.043264e+08,600570.XSHG,NaN,NaN,0.1565,...,NaN,NaN,5.173393e+07,2010-12-31,2010-12-31,1.048749e+08,3.096945e+08,3.572915e+08,1.084017e+08,NaN
24,5ac57fb02e565406381d08b7,6.092596e+07,1.847453e+04,0.0655,-3.274922e+05,4.070879e+07,600570.XSHG,NaN,NaN,0.0655,...,NaN,NaN,2.878803e+07,2011-03-31,2011-03-31,4.038130e+07,1.281578e+08,1.596664e+08,4.334764e+07,NaN
25,5ac57fb02e565406381d08b8,8.860041e+07,4.674910e+06,0.0450,3.082941e+06,1.939936e+07,600570.XSHG,NaN,NaN,0.0450,...,NaN,NaN,3.323484e+07,2011-06-30,2011-06-30,2.248230e+07,1.951570e+08,2.100290e+08,3.541586e+07,NaN
26,5ac57fb02e565406381d08b9,9.171340e+07,6.000000e+03,0.0605,-1.931755e+06,3.853734e+07,600570.XSHG,NaN,NaN,0.0605,...,NaN,NaN,4.146168e+07,2011-09-30,2011-09-30,3.660559e+07,1.645998e+08,1.878616e+08,3.582275e+07,NaN
27,5ac57fb02e565406381d08ba,1.801892e+08,3.616142e+06,0.2390,5.365554e+06,1.706327e+08,600570.XSHG,NaN,NaN,0.2390,...,NaN,NaN,7.084292e+07,2011-12-31,2011-12-31,1.759983e+08,3.706134e+08,4.906363e+08,1.712592e+08,NaN
28,5ac57fb02e565406381d08bb,8.269467e+07,-4.464517e+05,0.0500,5.112116e+05,1.767486e+07,600570.XSHG,NaN,NaN,0.0500,...,NaN,NaN,3.160459e+07,2012-03-31,2012-03-31,1.818607e+07,1.354821e+08,1.422648e+08,3.418722e+07,NaN
29,5ac57fb02e565406381d08bc,1.136536e+08,7.355792e+06,0.0400,-4.523277e+05,2.180667e+07,600570.XSHG,NaN,NaN,0.0400,...,NaN,NaN,4.086143e+07,2012-06-30,2012-06-30,2.135434e+07,2.097509e+08,2.156263e+08,3.390782e+07,NaN
30,5ac57fb02e565406381d08bd,1.157561e+08,1.332350e+03,0.0500,1.847703e+06,4.054506e+07,600570.XSHG,NaN,NaN,0.0500,...,NaN,NaN,4.373194e+07,2012-09-30,2012-09-30,4.239276e+07,1.992396e+08,1.961722e+08,2.989635e+07,NaN
31,5ac57fb02e565406381d08be,1.941328e+08,2.278108e+06,0.1800,1.005796e+07,7.868710e+07,600570.XSHG,NaN,NaN,0.1800,...,NaN,NaN,7.416365e+07,2012-12-31,2012-12-31,8.874506e+07,4.068516e+08,4.520283e+08,1.232218e+08,NaN
32,5ac57fb02e565406381d08bf,9.848443e+07,-9.510166e+06,0.0600,-2.325110e+06,6.354569e+07,600570.XSHG,NaN,NaN,0.0600,...,NaN,NaN,3.219553e+07,2013-03-31,2013-03-31,6.122058e+07,1.498439e+08,1.719325e+08,4.043195e+07,NaN
33,5ac57fb02e565406381d08c0,1.168314e+08,4.447159e+06,0.0700,2.047870e+05,4.849819e+07,600570.XSHG,NaN,NaN,0.0700,...,NaN,NaN,3.393863e+07,2013-06-30,2013-06-30,4.870298e+07,2.283300e+08,2.493508e+08,4.934582e+07,NaN
34,5ac57fb02e565406381d08c1,1.226154e+08,0.000000e+00,0.0800,3.124965e+05,5.286367e+07,600570.XSHG,NaN,NaN,0.0800,...,NaN,NaN,4.850965e+07,2013-09-30,2013-09-30,5.317617e+07,2.002277e+08,2.244718e+08,7.485840e+07,NaN
35,5ac57fb02e565406381d08c2,2.351538e+08,-1.121188e+06,0.3100,1.793916e+07,1.952787e+08,600570.XSHG,NaN,NaN,0.3100,...,NaN,NaN,9.758727e+07,2013-12-31,2013-12-31,2.132179e+08,4.482614e+08,5.647921e+08,2.035822e+08,NaN
36,5ac57fb02e565406381d08c3,1.257998e+08,NaN,0.0900,-2.786795e+06,6.297603e+07,600570.XSHG,NaN,NaN,0.0900,...,NaN,NaN,4.733678e+07,2014-03-31,2014-03-31,6.018924e+07,1.884408e+08,2.017034e+08,5.921796e+07,NaN
37,5ac57fb02e565406381d08c4,1.516363e+08,5.117408e+06,0.0900,-2.213100e+06,4.176991e+07,600570.XSHG,NaN,NaN,0.0900,...,NaN,NaN,6.525140e+07,2014-06-30,2014-06-30,3.955681e+07,2.521245e+08,2.609672e+08,5.877667e+07,NaN
38,5ac57fb02e565406381d08c5,1.883604e+08,0.000000e+00,0.0300,2.812352e+06,4.999361e+07,600570.XSHG,NaN,NaN,0.0300,...,NaN,NaN,1.047286e+08,2014-09-30,2014-09-30,5.280596e+07,3.189146e+08,3.082180e+08,5.096428e+07,NaN
39,5ac57fb02e565406381d08c6,3.352965e+08,7.862399e+04,0.3600,-3.980238e+06,2.183323e+08,600570.XSHG,NaN,NaN,0.3600,...,NaN,NaN,1.401018e+08,2014-12-31,2014-12-31,2.143521e+08,5.050815e+08,6.509505e+08,2.171650e+08,NaN
40,5ac57fb02e565406381d08c7,1.584945e+08,NaN,0.1100,1.429527e+06,1.135436e+08,600570.XSHG,NaN,NaN,0.1100,...,NaN,NaN,8.756997e+07,2015-03-31,2015-03-31,1.149732e+08,2.648900e+08,2.741318e+08,7.809997e+07,NaN
41,5ac57fb02e565406381d08c8,2.800698e+08,8.130811e+06,0.2300,2.183161e+07,1.771184e+08,600570.XSHG,NaN,NaN,0.2300,...,NaN,NaN,1.511712e+08,2015-06-30,2015-06-30,1.989500e+08,5.242981e+08,6.342701e+08,1.753289e+08,NaN
42,5ac57fb02e565406381d08c9,3.721475e+08,-6.018500e+05,-0.0800,-5.895487e+07,-8.562011e+07,600570.XSHG,NaN,NaN,-0.0800,...,NaN,NaN,1.667889e+08,2015-09-30,2015-09-30,-1.445750e+08,5.540822e+08,3.899162e+08,-1.033324e+08,NaN
43,5ac57fb02e565406381d08ca,2.468927e+08,1.164646e+08,0.4700,3.123601e+07,3.495755e+08,600570.XSHG,NaN,NaN,0.4700,...,NaN,NaN,1.762892e+08,2015-12-31,2015-12-31,3.808116e+08,6.161181e+08,9.272142e+08,3.650838e+08,NaN
44,5ac57fb02e565406381d08cb,2.026724e+08,-2.479232e+04,0.1200,-7.001210e+06,3.477532e+07,600570.XSHG,NaN,NaN,0.1200,...,NaN,NaN,1.163337e+08,2016-03-31,2016-03-31,2.777411e+07,3.293775e+08,3.369861e+08,7.014102e+07,NaN
45,5ac57fb02e565406381d08cc,2.976088e+08,2.151423e+06,0.1500,-1.178011e+07,1.002529e+08,600570.XSHG,NaN,NaN,0.1500,...,NaN,NaN,1.279108e+08,2016-06-30,2016-06-30,8.847283e+07,4.608934e+08,4.835933e+08,8.928306e+07,NaN
46,5ac57fb02e565406381d08cd,3.298132e+08,-1.092348e+05,0.0700,5.691626e+06,4.382338e+07,600570.XSHG,NaN,NaN,0.0700,...,NaN,NaN,2.008967e+08,2016-09-30,2016-09-30,4.951500e+07,5.665901e+08,5.168427e+08,2.343213e+07,NaN
47,5ac57fb02e565406381d08ce,5.047452e+08,2.120523e+06,-0.3000,-5.661848e+07,-1.610010e+08,600570.XSHG,NaN,NaN,-0.3000,...,NaN,NaN,2.178740e+08,2016-12-31,2016-12-31,-2.176195e+08,7.849189e+08,8.327441e+08,-2.428427e+08,NaN
48,5ac57fb02e565406381d08cf,2.971846e+08,-1.289054e+06,0.0700,-1.193785e+06,7.429376e+07,600570.XSHG,NaN,NaN,0.0700,...,NaN,NaN,1.580180e+08,2017-03-31,2017-03-31,7.309998e+07,4.778144e+08,4.428547e+08,4.108078e+07,NaN
49,5ac57fb02e565406381d08d0,3.598160e+08,1.326131e+07,0.3000,5.240964e+06,1.782194e+08,600570.XSHG,NaN,NaN,0.3000,...,NaN,NaN,1.869998e+08,2017-06-30,2017-06-30,1.834603e+08,5.923973e+08,6.374332e+08,2.054813e+08,NaN
50,5ac57fb02e565406381d08d1,4.150214e+08,-3.705016e+06,0.1000,1.747525e+07,1.068077e+08,600570.XSHG,NaN,NaN,0.1000,...,NaN,NaN,2.148271e+08,2017-09-30,2017-09-30,1.242829e+08,6.459525e+08,5.702901e+08,8.904553e+07,NaN

In [41]:
df['pubDate'] = pd.to_datetime(df['pubDate'])

In [42]:
incomedf = df[df.pubDate <= '2017-06-06'][-4:]

In [43]:
column_sum = incomedf['net_profit'].sum()

In [45]:
df = pd.read_csv("c:\\stockdata\\guben\\600570.csv")

In [48]:
df.rename(columns={'Unnamed: 0':'date'})

,date,circulation_a,management_circulation,non_circulation_a,total_a,total
0,2003-12-16,17000000.0,NaN,51000000.0,68000000.0,68000000.0
1,2003-12-17,17000000.0,NaN,51000000.0,68000000.0,68000000.0
2,2003-12-18,17000000.0,NaN,51000000.0,68000000.0,68000000.0
3,2003-12-19,17000000.0,NaN,51000000.0,68000000.0,68000000.0
4,2003-12-22,17000000.0,NaN,51000000.0,68000000.0,68000000.0
5,2003-12-23,17000000.0,NaN,51000000.0,68000000.0,68000000.0
6,2003-12-24,17000000.0,NaN,51000000.0,68000000.0,68000000.0
7,2003-12-25,17000000.0,NaN,51000000.0,68000000.0,68000000.0
8,2003-12-26,17000000.0,NaN,51000000.0,68000000.0,68000000.0
9,2003-12-29,17000000.0,NaN,51000000.0,68000000.0,68000000.0
10,2003-12-30,17000000.0,NaN,51000000.0,68000000.0,68000000.0
11,2003-12-31,17000000.0,NaN,51000000.0,68000000.0,68000000.0
12,2004-01-02,17000000.0,NaN,51000000.0,68000000.0,68000000.0
13,2004-01-05,17000000.0,NaN,51000000.0,68000000.0,68000000.0
14,2004-01-06,17000000.0,NaN,51000000.0,68000000.0,68000000.0
15,2004-01-07,17000000.0,NaN,51000000.0,68000000.0,68000000.0
16,2004-01-08,17000000.0,NaN,51000000.0,68000000.0,68000000.0
17,2004-01-09,17000000.0,NaN,51000000.0,68000000.0,68000000.0
18,2004-01-12,17000000.0,NaN,51000000.0,68000000.0,68000000.0
19,2004-01-13,17000000.0,NaN,51000000.0,68000000.0,68000000.0
20,2004-01-14,17000000.0,NaN,51000000.0,68000000.0,68000000.0
21,2004-01-15,17000000.0,NaN,51000000.0,68000000.0,68000000.0
22,2004-01-16,17000000.0,NaN,51000000.0,68000000.0,68000000.0
23,2004-01-29,17000000.0,NaN,51000000.0,68000000.0,68000000.0
24,2004-01-30,17000000.0,NaN,51000000.0,68000000.0,68000000.0
25,2004-02-02,17000000.0,NaN,51000000.0,68000000.0,68000000.0
26,2004-02-03,17000000.0,NaN,51000000.0,68000000.0,68000000.0
27,2004-02-04,17000000.0,NaN,51000000.0,68000000.0,68000000.0
28,2004-02-05,17000000.0,NaN,51000000.0,68000000.0,68000000.0
29,2004-02-06,17000000.0,NaN,51000000.0,68000000.0,68000000.0
...,...,...,...,...,...,...
3433,2018-01-29,617805180.0,NaN,0.0,617805180.0,617805180.0
3434,2018-01-30,617805180.0,NaN,0.0,617805180.0,617805180.0
3435,2018-01-31,617805180.0,NaN,0.0,617805180.0,617805180.0
3436,2018-02-01,617805180.0,NaN,0.0,617805180.0,617805180.0
3437,2018-02-02,617805180.0,NaN,0.0,617805180.0,617805180.0
3438,2018-02-05,617805180.0,NaN,0.0,617805180.0,617805180.0
3439,2018-02-06,617805180.0,NaN,0.0,617805180.0,617805180.0
3440,2018-02-07,617805180.0,NaN,0.0,617805180.0,617805180.0
3441,2018-02-08,617805180.0,NaN,0.0,617805180.0,617805180.0
3442,2018-02-09,617805180.0,NaN,0.0,617805180.0,617805180.0
3443,2018-02-12,617805180.0,NaN,0.0,617805180.0,617805180.0
3444,2018-02-13,617805180.0,NaN,0.0,617805180.0,617805180.0
3445,2018-02-14,617805180.0,NaN,0.0,617805180.0,617805180.0
3446,2018-02-22,617805180.0,NaN,0.0,617805180.0,617805180.0
3447,2018-02-23,617805180.0,NaN,0.0,617805180.0,617805180.0
3448,2018-02-26,617805180.0,NaN,0.0,617805180.0,617805180.0
3449,2018-02-27,617805180.0,NaN,0.0,617805180.0,617805180.0
3450,2018-02-28,617805180.0,NaN,0.0,617805180.0,617805180.0
3451,2018-03-01,617805180.0,NaN,0.0,617805180.0,617805180.0
3452,2018-03-02,617805180.0,NaN,0.0,617805180.0,617805180.0
3453,2018-03-05,617805180.0,NaN,0.0,617805180.0,617805180.0
3454,2018-03-06,617805180.0,NaN,0.0,617805180.0,617805180.0
3455,2018-03-07,617805180.0,NaN,0.0,617805180.0,617805180.0
3456,2018-03-08,617805180.0,NaN,0.0,617805180.0,617805180.0
3457,2018-03-09,617805180.0,NaN,0.0,617805180.0,617805180.0
3458,2018-03-12,617805180.0,NaN,0.0,617805180.0,617805180.0
3459,2018-03-13,617805180.0,NaN,0.0,617805180.0,617805180.0
3460,2018-03-14,617805180.0,NaN,0.0,617805180.0,617805180.0
3461,2018-03-15,617805180.0,NaN,0.0,617805180.0,617805180.0
3462,2018-03-16,617805180.0,NaN,0.0,617805180.0,617805180.0